### ISSUE TITLE
公众号 oauth 授权的时候经常获取不到appid, 回调页面会报 缺少参数 appid, 多试几次会好

### ISSUE THREAD

**Issue by shopshow** [Eric-Guo/wechat#155]
下面是授权的代码片段
```ruby
    wechat_oauth2('snsapi_userinfo') do |openid|
      user_info = wechat.user(openid)
      user = User.find_or_initialize_by(wx_openid: openid) do |user|
        user.wx_unionid = user_info['unionid']
        user.login      = user_info['nickname']
        user.gender     = user_info['sex'].to_i
        user.mobile     = "wx_#{SecureRandom.hex(5)}"
        user.password   = SecureRandom.hex(5)
      end
```

**Comment by shopshow** [comment]
wechat.yml 配置

```yaml
default: &default
# Or if using public account, only need above two line
  appid: xxxxx
  secret: "xxxxx"
  access_token: "/var/tmp/wechat_access_token"
  jsapi_ticket: "/var/tmp/wechat_jsapi_ticket"

production:
  <<: *default
```
