### ISSUE TITLE
File exists but `Need create ~/.wechat.yml with wechat appid and secret or running at rails root folder so wechat can read config/wechat.yml`

### ISSUE THREAD

**Issue by imWildCat** [Eric-Guo/wechat#189]
> Ruby version: `ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]`
> Installed by `rbenv` 1.1.0

In my Mac, both `~/.wechat.yml` and `config/wechat.yml` exist. However it said:

```shell
➜  ysera git:(master) ✗ bundle exec wechat
bundler: failed to load command: wechat (/Users/wildcat/.rbenv/versions/2.4.1/bin/wechat)
RuntimeError: Need create ~/.wechat.yml with wechat appid and secret or running at rails root folder so wechat can read config/wechat.yml
  /Users/wildcat/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/wechat-0.8.8/lib/wechat/api_loader.rb:15:in `with'
  /Users/wildcat/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/wechat-0.8.8/bin/wechat:41:in `<class:App>'
  /Users/wildcat/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/wechat-0.8.8/bin/wechat:18:in `<top (required)>'
  /Users/wildcat/.rbenv/versions/2.4.1/bin/wechat:22:in `load'
  /Users/wildcat/.rbenv/versions/2.4.1/bin/wechat:22:in `<top (required)>'

➜  ysera git:(master) ✗ wechat
^[[A/Users/wildcat/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/wechat-0.8.8/lib/wechat/api_loader.rb:15:in `with': Need create ~/.wechat.yml with wechat appid and secret or running at rails root folder so wechat can read config/wechat.yml (RuntimeError)
	from /Users/wildcat/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/wechat-0.8.8/bin/wechat:41:in `<class:App>'
	from /Users/wildcat/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/wechat-0.8.8/bin/wechat:18:in `<top (required)>'
	from /Users/wildcat/.rbenv/versions/2.4.1/bin/wechat:22:in `load'
	from /Users/wildcat/.rbenv/versions/2.4.1/bin/wechat:22:in `<main>'
```

**Comment by imWildCat** [comment]
```yml
default: &default
#  corpid: "corpid"
#  corpsecret: "corpsecret"
#  agentid:  1
# Or if using public account, only need above two line
  appid: <%= ENV['WECHAT_MP_ID'] %>
  secret: <%= ENV['WECHAT_MP_SECRET'] %>
  token: <%= ENV['WECHAT_MP_TOKEN'] %>
  access_token: "C:/Users/[username]/wechat_access_token"
  encrypt_mode: false # if true must fill encoding_aes_key
  encoding_aes_key:  <%= ENV['WECHAT_MP_AES_KEY'] %>
  jsapi_ticket: "C:/Users/[user_name]/wechat_jsapi_ticket"
```

Solved: It is because that the format of my `WeChat.yml` file cannot satisfy the validation. The error message should be improve in order to distinguish format error or file existence error.
