### ISSUE TITLE
Wechat::ResponseError: invalid button size (40016)

### ISSUE THREAD

**Issue by dannio** [Eric-Guo/wechat#210]
I generated the standard menu example and added 2 more buttons to it and wechat refuses to take my request:

````
# More option see https://github.com/Eric-Guo/wechat#menu-create
button:
 -
  type: "view"
  name: "Home"
  url:  "https://www.xxxxx.com/"
 -
  name: "Query"
  sub_button:
   -
    type: "scancode_waitmsg"
    name: "绑定用餐二维码"
    key: "BINDING_QR_CODE"
   -
    type: "click"
    name: "预订午餐"
    key:  "BOOK_LUNCH"
   -
    type: "click"
    name: "预订晚餐"
    key:  "BOOK_DINNER"
 -
  type: "view"
  name: "Home"
  url:  "https://www.xxxxx.com/"
````
