### ISSUE TITLE
wechat_api 接口对自定义小程序配置无法正确读取

### ISSUE THREAD

**Issue by Msms-NJ** [Eric-Guo/wechat#280]
如果使用 wechat_api 调用小程序相关接口，无法读取自定义的type类型。
例如：
如果在wechat.yml 中的 default 配置下配置 type 为 mp，则 wechat 会被初始化为 MpApi。
如果在wechat.yml 中自定义 cust_miniapp 配置下配置 type 为 mp，则 wechat 会被初始为默认值。

**Comment by Eric-Guo** [comment]
default下不要配置type的情况下[自定义配置下的type才会起效](https://github.com/Eric-Guo/wechat/blob/master/lib/wechat/api_loader.rb#L11)。

**Comment by Msms-NJ** [comment]
我这边 default 没有配置 type 的情况下，自定义下的 type 仍然读取不到。
这是我这边配置文件
```yml
default: &default
  corpid: "corpid"
  corpsecret: "corpsecret"
  agentid:  1
  appid: "appid"
  secret: "secret"
  token:    "my_token"
  access_token: "C:/Users/[username]/wechat_access_token"
  encrypt_mode: false # if true must fill encoding_aes_key
  encoding_aes_key:  "my_encoding_aes_key"
  jsapi_ticket: "C:/Users/[user_name]/wechat_jsapi_ticket"

cust_miniapp_development:
  appid: "appid"
  secret: "secrets"
  type: 'mp'
```

在 controller 里的简单调用
```ruby
  class WechatAppController < ActionController::API

    wechat_api(account: :cust_miniapp)

    def code_to_session
      res = wechat.jscode2session(params[:code])
      render json: res
    rescue StandardError => e
      render json: { error: e.message}, status: :internal_server_error
    end


  end
```
返回的错误信息就是
```json
{
    "error": "undefined method `jscode2session' for #<Wechat::Api:0x00007fcf24b1faf8>"
}
```

**Comment by Eric-Guo** [comment]
你需要写成

```yml
default: &default
  corpid: "corpid"
  corpsecret: "corpsecret"
  agentid:  1
  appid: "appid"
  secret: "secret"
  token:    "my_token"
  access_token: "C:/Users/[username]/wechat_access_token"
  encrypt_mode: false # if true must fill encoding_aes_key
  encoding_aes_key:  "my_encoding_aes_key"
  jsapi_ticket: "C:/Users/[user_name]/wechat_jsapi_ticket"

development:
  <<: *default
  trusted_domain_fullname: "https://ericguo.ggrok.com"

cust_miniapp_development:
  appid: "appid"
  secret: "secrets"
  type: 'mp'
```

因为这里的default只是挂着，你需要真的到development里面引用它。
