### ISSUE TITLE
如何调用mp_api下关于小程序的API?

### ISSUE THREAD

**Issue by bing-zhub** [Eric-Guo/wechat#304]
在调用过程中出现找不到该方法的报错, 请您帮助. 如果有可能的话, 希望针对此类API对wechat-starter项目进行更新.  谢谢!
![undefined method](https://user-images.githubusercontent.com/39323503/139641588-f578c56f-ed07-48ef-a0f2-c237a6f2cca2.png)

**Comment by bing-zhub** [comment]
翻issue找到了解决方法.  
``` yaml
default: &default
  corpid: "corpid"
  corpsecret: "corpsecret"
  agentid: 1
  appid: "appid"
  secret: "secret"
  token: "my_token"
  access_token: "C:/Users/[username]/wechat_access_token"
  encrypt_mode: false # if true must fill encoding_aes_key
  encoding_aes_key: "my_encoding_aes_key"
  jsapi_ticket: "C:/Users/[user_name]/wechat_jsapi_ticket"

development:
  <<: *default
  trusted_domain_fullname: "https://ericguo.ggrok.com"

cust_miniapp_development:
  appid: "appid"
  secret: "secret"
  type: "mp"

```

``` ruby
def login
    begin 
      @result = Wechat.api('cust_miniapp').jscode2session(params[:code])

    rescue => err
      @result = {error: err.message}
    end 
    render json: @result
  end
```
