### ISSUE TITLE
项目内执行wechat出错，Ruby2.1.5,ActiveSupport 4.2.1

### ISSUE THREAD

**Issue by xprimes** [Eric-Guo/wechat#58]
```
λ ~/dev/lit/ wechat2* wechat
/Users/xprimes/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.1/lib/active_support/core_ext/module/deprecation.rb:21:in `deprecate': uninitialized constant ActiveSupport::Deprecation (NameError)
	from /Users/xprimes/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.1/lib/active_support/core_ext/class/delegating_attributes.rb:26:in `<class:Class>'
	from /Users/xprimes/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.1/lib/active_support/core_ext/class/delegating_attributes.rb:6:in `<top (required)>'
	from /Users/xprimes/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.1/lib/active_support/core_ext/class.rb:2:in `require'
	from /Users/xprimes/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.1/lib/active_support/core_ext/class.rb:2:in `<top (required)>'
	from /Users/xprimes/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.1/lib/active_support/core_ext.rb:2:in `require'
	from /Users/xprimes/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.1/lib/active_support/core_ext.rb:2:in `block in <top (required)>'
	from /Users/xprimes/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.1/lib/active_support/core_ext.rb:1:in `each'
	from /Users/xprimes/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.1/lib/active_support/core_ext.rb:1:in `<top (required)>'
	from /Users/xprimes/.rvm/gems/ruby-2.1.5/gems/wechat-0.6.0/bin/wechat:10:in `require'
	from /Users/xprimes/.rvm/gems/ruby-2.1.5/gems/wechat-0.6.0/bin/wechat:10:in `<top (required)>'
	from /Users/xprimes/.rvm/gems/ruby-2.1.5/bin/wechat:23:in `load'
	from /Users/xprimes/.rvm/gems/ruby-2.1.5/bin/wechat:23:in `<main>'
	from /Users/xprimes/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
	from /Users/xprimes/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by Eric-Guo** [comment]
无法复现，请尝试在项目内运行`rails g wechat:install`，然后比较一下config/wechat.yml文件的内容？

**Comment by xprimes** [comment]
嗯，项目内运行 rails g wechat:install 再执行，wechat就出错了
无论怎么修改 config/wechat.yml 都会直接出错
```
default: &default
# Or if using public account, only need above two line
 appid: 'wxdc7aaa425156987b'
 secret: 'd06b5527f4b931a0cd9fd314274743f'
 token:  "SQBQirYFxoLCUOF8PXUyuVbvPNTLckk"
 access_token: "/var/tmp/wechat_access_token"

production:
# Or if using public account, only need above two line
#  appid:
#  secret:
  token:      <%= ENV['WECHAT_TOKEN'] %>
  access_token:  <%= ENV['WECHAT_ACCESS_TOKEN'] %>
  encoding_aes_key:  <%= ENV['WECHAT_ENCODING_AES_KEY'] %>

development:
  <<: *default

test:
  <<: *default
```
