### ISSUE TITLE
希望on :click 可以不用with

### ISSUE THREAD

**Issue by kikyous** [Eric-Guo/wechat#93]
现在一点都不灵活啊

**Comment by Eric-Guo** [comment]
你可以使用event，写`on :event, with: /^BUTTON_(\d+)$/`，这个支持正则的，不过注意性能稍差（on :click是hash查找的，这个是遍历匹配的）

**Comment by kikyous** [comment]
哦，谢谢。对微信消息还是不熟悉

**Comment by libuchao** [comment]
@Eric-Guo 你好，`on :event, with: /^BUTTON_(\d+)$/` 这里是根据 button 的 name 匹配正则的么？后面的 proc 中可以获取到 click 的 key 么？

**Comment by Eric-Guo** [comment]
应该可以的，你可以试试

**Comment by libuchao** [comment]
@Eric-Guo 

```yml
    name: BUTTON_联系我们
    type: click
    key: BUTTON_CONTACT_US
```

```ruby
  on :event, with: '/^BUTTON_(\w+)$/' do |request, key|
    request.reply.text "User click #{key}"
  end
```

你好，这样好像匹配不到，我的写法有问题么？
